### ISSUE TITLE
Decision: how to measure the size of a problem

### ISSUE THREAD

**Issue by GiggleLiu** [GiggleLiu/ProblemReductions.jl#86]
So that we can measure the performance of a reduction rule properly.

**Comment by c-allergic** [comment]
- Vertex Covering to Set Covering
For a vertex covering problem on graph $G = (V,E)$ ，after reduction, we would get a set covering problem, containing the  universe $U$, whose size is the same as the number of edges in $G$ and the number of subsets equals to the number of vertices in source problem. 
So the reduction complexity should be 1 since the size is the same.

**Comment by GiggleLiu** [comment]
We use a named tuple to annotate the size of a problem, e.g. (num_vertices = 5, num_edges = 10)
